AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Template for cc-test

Parameters:
  ApiStage:
    Type: String
    Default: Test
  
Globals:
  Function:
    Timeout: 3

Resources:
  UsersApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      StageName: !Ref ApiStage
  UsersFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: users/
      Handler: app.lambdaHandler
      Runtime: nodejs20.x
      Architectures:
        - x86_64
      Environment:
        Variables:
          USERS_TABLE_NAME: !Ref UsersTable
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref UsersTable
      Events:
        UsersGet:
          Type: HttpApi
          Properties:
            ApiId: !Ref UsersApi
            Path: /users
            Method: get
        UsersPost:
          Type: HttpApi
          Properties:
            ApiId: !Ref UsersApi
            Path: /users
            Method: post
        UsersPatch:
          Type: HttpApi
          Properties:
            ApiId: !Ref UsersApi
            Path: /users/{id}
            Method: patch
        UsersDelete:
          Type: HttpApi
          Properties:
            ApiId: !Ref UsersApi
            Path: /users/{id}
            Method: delete
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints: 
        - src/app.ts
  UsersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
      - AttributeName: id
        AttributeType: S
      KeySchema:
      - AttributeName: id
        KeyType: HASH
      BillingMode: PAY_PER_REQUEST

Outputs:
  UsersApiEndpoint:
    Description: "API Gateway endpoint URL for UploadFileFunction"
    Value: !Sub "https://${UsersApi}.execute-api.${AWS::Region}.amazonaws.com/${ApiStage}/users/"
  UsersFunction:
    Description: "Users Lambda Function ARN"
    Value: !GetAtt UsersFunction.Arn
  UsersFunctionIamRole:
    Description: "Implicit IAM Role created for Users function"
    Value: !GetAtt UsersFunctionRole.Arn
  UsersTable:
    Description: "DynamoDb Users Table"
    Value: !Ref UsersTable
