AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Template for cc-test
  
Globals:
  Function:
    Timeout: 3

Resources:
  UsersApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      StageName: Dev
  UsersFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: users/
      Handler: app.lambdaHandler
      Runtime: nodejs20.x
      Architectures:
        - x86_64
      Environment:
        Variables:
          USERS_TABLE_NAME: !Ref UsersTable
      Policies:
        - DynamoDBWritePolicy:
            TableName: !Ref UsersTable
      Events:
        UsersGet:
          Type: HttpApi
          Properties:
            RestApiId: !Ref UsersApi
            Path: /users
            Method: get
        UsersDelete:
          Type: HttpApi
          Properties:
            RestApiId: !Ref UsersApi
            Path: /users/{id}
            Method: delete
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints: 
        - app.ts
  UsersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
      - AttributeName: id
        AttributeType: S
      - AttributeName: name
        AttributeType: S
      - AttributeName: email
        AttributeType: S
      KeySchema:
      - AttributeName: id
        KeyType: HASH
      BillingMode: PAY_PER_REQUEST

Outputs:
  UsersApi:
    Description: "API Gateway endpoint URL for Prod stage for Users function"
    Value: !GetAtt UsersApi.Arn
  UsersFunction:
    Description: "Users Lambda Function ARN"
    Value: !GetAtt UsersFunction.Arn
  UsersFunctionIamRole:
    Description: "Implicit IAM Role created for Users function"
    Value: !GetAtt UsersFunctionRole.Arn
  UsersTable:
    Description: "DynamoDb Users Table"
    Value: !Ref UsersTable
